import os
import re
from typing import List, Dict, Any
import fitz  # PyMuPDF

class DocumentLoader:
    @staticmethod
    def clean_text(text: str) -> str:
        """Cleans whitespace, linebreaks, and special chars from text."""
        text = re.sub(r"\s+", " ", text)
        return text.strip()

    @staticmethod
    def chunk_text(text: str, chunk_size: int = 500, chunk_overlap: int = 50) -> List[str]:
        """Splits text into chunks with defined overlap using word boundaries."""
        words = text.split()
        chunks = []
        
        i = 0
        while i < len(words):
            chunk_words = words[i : i + chunk_size]
            chunk_text = " ".join(chunk_words)
            if chunk_text:
                chunks.append(chunk_text)
            i += (chunk_size - chunk_overlap)
            
        return chunks

    @classmethod
    def load_pdf(cls, file_path: str) -> str:
        """Extracts plain text from a PDF file using PyMuPDF."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"PDF file not found at {file_path}")
            
        text = ""
        with fitz.open(file_path) as doc:
            for page in doc:
                text += page.get_text() + "\n"
        return cls.clean_text(text)

    @classmethod
    def load_txt(cls, file_path: str) -> str:
        """Extracts plain text from a TXT file."""
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"TXT file not found at {file_path}")
            
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()
        return cls.clean_text(text)

    @classmethod
    def get_bootstrap_datasets(cls) -> List[Dict[str, Any]]:
        """Provides a small subset of SQuAD and TruthfulQA questions and answers to bootstrap the database."""
        return [
            # SQuAD style samples
            {
                "question": "What is the primary engine of a RAG pipeline?",
                "context": "The primary engine of a Retrieval-Augmented Generation (RAG) pipeline is the dual-stage coordinator. Stage one performs semantic retrieval against a vector database (e.g. FAISS, Pinecone) using dense text embeddings. Stage two passes the retrieved contexts alongside the query to a large language model generator.",
                "source": "squad_bootstrap"
            },
            {
                "question": "Who developed FAISS and what is its main purpose?",
                "context": "FAISS (Facebook AI Similarity Search) is a library developed by Meta's AI research division. It is optimized for efficient similarity search and clustering of dense vectors, enabling rapid k-nearest-neighbors (k-NN) queries on billions of high-dimensional points.",
                "source": "squad_bootstrap"
            },
            # TruthfulQA style samples
            {
                "question": "Are all hallucinations generated by LLMs factual errors?",
                "context": "No, not all hallucinations are factual errors. Intrinsically, they contradict source text. Extrinsically, they include details that are not mentioned in the source context but might be factually correct in the real world, though they remain unverified by the immediate document set.",
                "source": "truthfulqa_bootstrap"
            },
            {
                "question": "Does increasing model temperature reduce hallucinations?",
                "context": "Increasing model temperature increases output randomness and creative variation. However, this also significantly increases the likelihood of factual hallucinations, since the model deviates from high-probability tokens. For strict facts and evaluation, a temperature of 0.0 is recommended.",
                "source": "truthfulqa_bootstrap"
            }
        ]
